[workspace]
members = ["common", "pidstat"]
resolver = "2"

[workspace.dependencies]
clap = { version = "4", features = ["derive"] }
rustix = "0.38"
strict-num = "0.2"
thiserror = "1"
time = "0.3"
tokio = { version = "1", features = ["full"] }
